mariadb10.3 10.4: fix compile error by hidden overloaded function
Since MariaDB 10.3.20/10.4.10, void handler::restore_auto_increment is
changed definition to virtual void function.
This commit fixes such a compile error.

  In file included from /home/travis/build/mroonga/mroonga/sql/log.h:20:0,
                   from /home/travis/build/mroonga/mroonga/sql/sql_class.h:27,
                   from /home/travis/build/mroonga/mroonga/storage/mroonga/mrn_mysql.h:58,
                   from /home/travis/build/mroonga/mroonga/storage/mroonga/ha_mroonga.cpp:23:
  /home/travis/build/mroonga/mroonga/sql/handler.h:3712:16: error: ‘virtual void handler::restore_auto_increment()’ was hidden [-Werror=overloaded-virtual]
     virtual void restore_auto_increment()

  In file included from /home/travis/build/mroonga/mroonga/storage/mroonga/ha_mroonga.cpp:88:0:
  /home/travis/build/mroonga/mroonga/storage/mroonga/ha_mroonga.hpp:837:8: error:   by ‘virtual void ha_mroonga::restore_auto_increment(ulonglong)’ [-Werror=overloaded-virtual]
     void restore_auto_increment(ulonglong prev_insert_id);
          ^